apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-service-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups: ["", "batch"]
  resources: ["pods", "nodes", "services", "jobs", "endpoints"]
  verbs: ["*"]
- apiGroups: ["vm.rancher.io"]
  resources: ["arptables", "credentials", "virtualmachines"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-service-account
  namespace: {{ .Release.Namespace }}
