apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    ranchervm-system: VirtualMachine
  name: virtualmachines.vm.rancher.io
spec:
  group: vm.rancher.io
  version: v1alpha1
  names:
    kind: VirtualMachine
    listKind: VirtualMachineList
    plural: virtualmachines
    shortNames: ["vm", "vms"]
    singular: virtualmachine
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    ranchervm-system: ARPTable
  name: arptables.vm.rancher.io
spec:
  group: vm.rancher.io
  version: v1alpha1
  names:
    kind: ARPTable
    listKind: ARPTableList
    plural: arptables
    shortNames: ["arp", "arps"]
    singular: arptable
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    ranchervm-system: Credential
  name: credentials.vm.rancher.io
spec:
  group: vm.rancher.io
  version: v1alpha1
  names:
    kind: Credential
    listKind: CredentialList
    plural: credentials
    shortNames: ["cred", "creds"]
    singular: credential
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    ranchervm-system: Setting
  name: settings.vm.rancher.io
spec:
  group: vm.rancher.io
  version: v1alpha1
  names:
    kind: Setting
    listKind: SettingList
    plural: settings
    singular: setting
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    ranchervm-system: MachineImage
  name: machineimages.vm.rancher.io
spec:
  group: vm.rancher.io
  version: v1alpha1
  names:
    kind: MachineImage
    listKind: MachineImageList
    plural: machineimages
    shortNames: ["img", "imgs"]
    singular: machineimage
  scope: Cluster
